'use strict';
const path = require('node:path');
const fs = require('node:fs');
const puppeteer = require('/home/ubuntu/projects/mcp-chromium-arm64/node_modules/puppeteer-core');
const executablePath = process.env.ABYSS_CHROME || '/home/ubuntu/.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux-arm64/chrome-headless-shell';
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const assert = (condition, message) => { if (!condition) throw new Error(message); console.log('PASS ' + message); };
let activeBrowser;
(async () => {
  const browser = activeBrowser = await puppeteer.launch({ executablePath, headless: true, args: ['--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--disable-software-rasterizer'], timeout: 15000 });
  const page = await browser.newPage();
  const issues = [], external = [];
  page.on('pageerror', error => issues.push(error.message));
  page.on('console', message => { if (['error','warn'].includes(message.type())) issues.push(message.type() + ': ' + message.text()); });
  page.on('request', request => { if (/^https?:/.test(request.url())) external.push(request.url()); });
  const url = 'file://' + path.resolve(__dirname, '../docs/index.html');
  await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 });
  await page.goto(url, { waitUntil: 'load' });
  await delay(600);
  assert(await page.title() === 'Abyss Racer', 'Local file title loads');
  assert(await page.evaluate(() => AR.inspect().state) === 'TITLE', 'Initial state is TITLE');
  await page.screenshot({ path: '/tmp/abyss-title-desktop.png' });
  await page.click('#title-help');
  assert(await page.$eval('#dialog-overlay', n => !n.hidden), 'How-to-play dialog opens');
  await page.keyboard.press('Escape');
  await page.click('#enter-garage');
  assert(await page.$$eval('.vehicle-grid .item-card', n => n.length) === 5, 'Garage contains five vehicles');
  await page.screenshot({ path: '/tmp/abyss-garage-desktop.png' });
  for (const tab of ['upgrades','stages','achievements','stats','vehicles']) {
    await page.click('#tab-' + tab);
    assert(await page.$eval('#tab-' + tab, n => n.getAttribute('aria-selected')) === 'true', tab + ' tab works');
  }
  await page.click('#start-run');
  await page.keyboard.down('ArrowRight');
  await delay(6500);
  await page.keyboard.up('ArrowRight');
  let status = await page.evaluate(() => AR.inspect());
  assert(status.state === 'RUNNING' && status.distance > 20, 'Throttle progresses during real browser frames: ' + status.distance.toFixed(1) + ' m');
  await page.screenshot({ path: '/tmp/abyss-running-desktop.png' });
  const oxygen = status.oxygen;
  await page.keyboard.press('Space');
  await delay(100);
  assert((await page.evaluate(() => AR.inspect())).oxygen < oxygen - 7, 'Ballast consumes oxygen');
  await page.keyboard.press('KeyP');
  status = await page.evaluate(() => AR.inspect());
  await delay(350);
  assert(await page.evaluate(() => AR.inspect().state) === 'PAUSED', 'Keyboard pause works');
  assert((await page.evaluate(() => AR.inspect())).oxygen === status.oxygen, 'Paused oxygen remains unchanged');
  await page.click('#resume-run');
  await page.click('#pause-button');
  await page.click('#end-run');
  assert(await page.evaluate(() => AR.inspect().state) === 'GAMEOVER', 'Ending dive displays summary');
  assert(await page.evaluate(() => AR.inspect().totalRuns) === 1, 'Run is banked exactly once');
  await page.screenshot({ path: '/tmp/abyss-summary-desktop.png' });
  await page.click('#back-garage');
  await page.reload({ waitUntil: 'load' });
  assert(await page.evaluate(() => AR.inspect().totalRuns) === 1, 'Progress persists across reload');
  // Seed a rich save to exercise purchase/UI flows without altering game code.
  await page.evaluate(() => { const save = new AR.Save(); save.data.pearls = 50000; save.save(); });
  await page.reload({ waitUntil: 'load' });
  await page.click('#enter-garage');
  await page.click('[data-action="vehicle"][data-id="truck"]');
  assert(await page.evaluate(() => AR.inspect().vehicle) === 'truck', 'Vehicle purchase equips the truck');
  await page.click('#tab-upgrades');
  await page.click('[data-action="upgrade"][data-id="oxygen"]');
  assert(await page.evaluate(() => new AR.Save().data.upgrades.truck.oxygen) === 1, 'Upgrade purchase persists per vehicle');
  await page.click('#tab-stages');
  await page.click('[data-action="stage"][data-id="ice"]');
  assert(await page.evaluate(() => AR.inspect().stage) === 'ice', 'Stage purchase selects Ice Shelf');
  await page.click('#tab-stats');
  await page.click('[data-action="reset"]');
  await page.click('#cancel-reset');
  assert(await page.evaluate(() => AR.inspect().totalRuns) === 1, 'Reset cancel preserves progress');
  await page.click('[data-action="reset"]');
  await page.click('#confirm-reset');
  assert(await page.evaluate(() => AR.inspect().pearls === 0 && AR.inspect().totalRuns === 0), 'Confirmed reset clears progression');
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
  await page.reload({ waitUntil: 'load' });
  await delay(200);
  await page.screenshot({ path: '/tmp/abyss-title-mobile.png' });
  assert(await page.evaluate(() => document.documentElement.scrollWidth === innerWidth), 'Mobile has no horizontal overflow');
  await page.click('#enter-garage');
  await page.click('#tab-vehicles');
  await page.screenshot({ path: '/tmp/abyss-garage-mobile.png' });
  assert(await page.$eval('#start-run', n => { const r = n.getBoundingClientRect(); return r.bottom <= innerHeight && r.right <= innerWidth; }), 'Mobile start button stays inside viewport');
  await page.click('#start-run');
  assert(await page.$eval('#touch-controls', n => getComputedStyle(n).display) === 'flex', 'Mobile pedals visible');
  await page.evaluate(() => {
    const gas = document.getElementById('pedal-gas');
    // Synthetic pointer events cannot be captured, so real CDP touch is used below.
    window.testGasRect = gas.getBoundingClientRect().toJSON();
  });
  const rect = await page.evaluate(() => window.testGasRect);
  const client = await page.createCDPSession();
  await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: rect.x + rect.width / 2, y: rect.y + rect.height / 2, id: 1 }] });
  await delay(1200);
  await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  assert((await page.evaluate(() => AR.inspect())).distance > 1, 'Real touch pedal accelerates rover');
  await page.screenshot({ path: '/tmp/abyss-running-mobile.png' });
  await page.setViewport({ width: 844, height: 390, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
  await delay(200);
  assert(await page.$eval('#pedal-gas', n => n.getBoundingClientRect().bottom <= innerHeight), 'Landscape rotation keeps controls accessible');
  await page.screenshot({ path: '/tmp/abyss-running-landscape.png' });
  assert(issues.length === 0, 'Zero browser console errors or warnings: ' + issues.join('; '));
  assert(external.length === 0, 'Zero external network requests');
  fs.writeFileSync(path.join(__dirname, 'browser.done'), 'PASS complete Chromium file:// desktop/mobile integration; controls, audio initialization, garage tabs, purchases, upgrades, save reload, reset, resize/orientation, zero app console errors/warnings or external network requests. Screenshots inspected separately.\n');
  await browser.close();
})().catch(async error => { console.error(error); if (activeBrowser) await activeBrowser.close(); process.exit(1); });
